// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 16.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace CRUDGen.Tts
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using CRUDGen.Lib;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "/home/osqyfr/Desktop/CRUDGen/CRUDGen/Tts/ServiceFile.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    public partial class ServiceFile : ServiceFileBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            
            #line 12 "/home/osqyfr/Desktop/CRUDGen/CRUDGen/Tts/ServiceFile.tt"

    var modelName = ModelNamesUtils.ConvertModelNameToVariableName(EntityName);

            
            #line default
            #line hidden
            this.Write("\nusing AutoMapper;\nusing ");
            
            #line 17 "/home/osqyfr/Desktop/CRUDGen/CRUDGen/Tts/ServiceFile.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(EntitiesNamespace));
            
            #line default
            #line hidden
            this.Write(";\nusing ");
            
            #line 18 "/home/osqyfr/Desktop/CRUDGen/CRUDGen/Tts/ServiceFile.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DtosNamespace));
            
            #line default
            #line hidden
            this.Write(";\nusing ");
            
            #line 19 "/home/osqyfr/Desktop/CRUDGen/CRUDGen/Tts/ServiceFile.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(RepositoryNamespace));
            
            #line default
            #line hidden
            this.Write(";\n\nnamespace ");
            
            #line 21 "/home/osqyfr/Desktop/CRUDGen/CRUDGen/Tts/ServiceFile.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ServicesNamespace));
            
            #line default
            #line hidden
            this.Write(";\n\npublic interface I");
            
            #line 23 "/home/osqyfr/Desktop/CRUDGen/CRUDGen/Tts/ServiceFile.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(EntityName));
            
            #line default
            #line hidden
            this.Write("Service : IService<");
            
            #line 23 "/home/osqyfr/Desktop/CRUDGen/CRUDGen/Tts/ServiceFile.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(EntityName));
            
            #line default
            #line hidden
            this.Write(", Create");
            
            #line 23 "/home/osqyfr/Desktop/CRUDGen/CRUDGen/Tts/ServiceFile.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(EntityName));
            
            #line default
            #line hidden
            this.Write("Dto, Update");
            
            #line 23 "/home/osqyfr/Desktop/CRUDGen/CRUDGen/Tts/ServiceFile.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(EntityName));
            
            #line default
            #line hidden
            this.Write("Dto>\n{\n}\n\npublic class ");
            
            #line 27 "/home/osqyfr/Desktop/CRUDGen/CRUDGen/Tts/ServiceFile.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(EntityName));
            
            #line default
            #line hidden
            this.Write("Service(I");
            
            #line 27 "/home/osqyfr/Desktop/CRUDGen/CRUDGen/Tts/ServiceFile.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(EntityName));
            
            #line default
            #line hidden
            this.Write("Repository ");
            
            #line 27 "/home/osqyfr/Desktop/CRUDGen/CRUDGen/Tts/ServiceFile.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelName));
            
            #line default
            #line hidden
            this.Write("Repository, IMapper mapper, IUnitOfWork unitOfWork) : I");
            
            #line 27 "/home/osqyfr/Desktop/CRUDGen/CRUDGen/Tts/ServiceFile.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(EntityName));
            
            #line default
            #line hidden
            this.Write("Service \n{\n   public async Task<IEnumerable<");
            
            #line 29 "/home/osqyfr/Desktop/CRUDGen/CRUDGen/Tts/ServiceFile.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(EntityName));
            
            #line default
            #line hidden
            this.Write(">> GetAllAsync() \n   {\n        return await ");
            
            #line 31 "/home/osqyfr/Desktop/CRUDGen/CRUDGen/Tts/ServiceFile.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(EntityName));
            
            #line default
            #line hidden
            this.Write("Repository.GetAllAsync();\n   }\n\n    public async Task<");
            
            #line 34 "/home/osqyfr/Desktop/CRUDGen/CRUDGen/Tts/ServiceFile.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(EntityName));
            
            #line default
            #line hidden
            this.Write("?> GetByIdAsync(int id)\n    {\n        return await ");
            
            #line 36 "/home/osqyfr/Desktop/CRUDGen/CRUDGen/Tts/ServiceFile.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelName));
            
            #line default
            #line hidden
            this.Write("Repository.GetByIdAsync(id);\n    }\n\n    public async Task<");
            
            #line 39 "/home/osqyfr/Desktop/CRUDGen/CRUDGen/Tts/ServiceFile.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(EntityName));
            
            #line default
            #line hidden
            this.Write("> CreateAsync(Create");
            
            #line 39 "/home/osqyfr/Desktop/CRUDGen/CRUDGen/Tts/ServiceFile.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(EntityName));
            
            #line default
            #line hidden
            this.Write("Dto create");
            
            #line 39 "/home/osqyfr/Desktop/CRUDGen/CRUDGen/Tts/ServiceFile.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(EntityName));
            
            #line default
            #line hidden
            this.Write("Dto) \n    {\n        var ");
            
            #line 41 "/home/osqyfr/Desktop/CRUDGen/CRUDGen/Tts/ServiceFile.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelName));
            
            #line default
            #line hidden
            this.Write(" = mapper.Map<");
            
            #line 41 "/home/osqyfr/Desktop/CRUDGen/CRUDGen/Tts/ServiceFile.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(EntityName));
            
            #line default
            #line hidden
            this.Write(">(create");
            
            #line 41 "/home/osqyfr/Desktop/CRUDGen/CRUDGen/Tts/ServiceFile.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(EntityName));
            
            #line default
            #line hidden
            this.Write("Dto);\n        await ");
            
            #line 42 "/home/osqyfr/Desktop/CRUDGen/CRUDGen/Tts/ServiceFile.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelName));
            
            #line default
            #line hidden
            this.Write("Repository.AddAsync(");
            
            #line 42 "/home/osqyfr/Desktop/CRUDGen/CRUDGen/Tts/ServiceFile.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelName));
            
            #line default
            #line hidden
            this.Write(");\n        await unitOfWork.SaveChangesAsync();\n        return ");
            
            #line 44 "/home/osqyfr/Desktop/CRUDGen/CRUDGen/Tts/ServiceFile.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelName));
            
            #line default
            #line hidden
            this.Write(";\n    }\n\n    public async Task<bool> UpdateAsync(int id, Update");
            
            #line 47 "/home/osqyfr/Desktop/CRUDGen/CRUDGen/Tts/ServiceFile.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(EntityName));
            
            #line default
            #line hidden
            this.Write("Dto update");
            
            #line 47 "/home/osqyfr/Desktop/CRUDGen/CRUDGen/Tts/ServiceFile.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(EntityName));
            
            #line default
            #line hidden
            this.Write("Dto)\n    {\n        var ");
            
            #line 49 "/home/osqyfr/Desktop/CRUDGen/CRUDGen/Tts/ServiceFile.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelName));
            
            #line default
            #line hidden
            this.Write(" = await ");
            
            #line 49 "/home/osqyfr/Desktop/CRUDGen/CRUDGen/Tts/ServiceFile.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelName));
            
            #line default
            #line hidden
            this.Write("Repository.GetByIdAsync(id);\n        \n        if (");
            
            #line 51 "/home/osqyfr/Desktop/CRUDGen/CRUDGen/Tts/ServiceFile.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelName));
            
            #line default
            #line hidden
            this.Write(" != null) \n        {\n            ");
            
            #line 53 "/home/osqyfr/Desktop/CRUDGen/CRUDGen/Tts/ServiceFile.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelName));
            
            #line default
            #line hidden
            this.Write(" = mapper.Map<");
            
            #line 53 "/home/osqyfr/Desktop/CRUDGen/CRUDGen/Tts/ServiceFile.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(EntityName));
            
            #line default
            #line hidden
            this.Write(">(update");
            
            #line 53 "/home/osqyfr/Desktop/CRUDGen/CRUDGen/Tts/ServiceFile.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(EntityName));
            
            #line default
            #line hidden
            this.Write("Dto);\n            ");
            
            #line 54 "/home/osqyfr/Desktop/CRUDGen/CRUDGen/Tts/ServiceFile.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelName));
            
            #line default
            #line hidden
            this.Write("Repository.Update(");
            
            #line 54 "/home/osqyfr/Desktop/CRUDGen/CRUDGen/Tts/ServiceFile.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelName));
            
            #line default
            #line hidden
            this.Write(");\n            await unitOfWork.SaveChangesAsync();\n            return true;\n        }\n        return false;\n    }\n\n    public async Task<bool> DeleteAsync(int id)\n    {\n        var ");
            
            #line 63 "/home/osqyfr/Desktop/CRUDGen/CRUDGen/Tts/ServiceFile.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelName));
            
            #line default
            #line hidden
            this.Write(" = await ");
            
            #line 63 "/home/osqyfr/Desktop/CRUDGen/CRUDGen/Tts/ServiceFile.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelName));
            
            #line default
            #line hidden
            this.Write("Repository.GetByIdAsync(id);\n        \n        if (");
            
            #line 65 "/home/osqyfr/Desktop/CRUDGen/CRUDGen/Tts/ServiceFile.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelName));
            
            #line default
            #line hidden
            this.Write(" != null)\n        {\n            ");
            
            #line 67 "/home/osqyfr/Desktop/CRUDGen/CRUDGen/Tts/ServiceFile.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelName));
            
            #line default
            #line hidden
            this.Write("Repository.Delete(");
            
            #line 67 "/home/osqyfr/Desktop/CRUDGen/CRUDGen/Tts/ServiceFile.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelName));
            
            #line default
            #line hidden
            this.Write(");\n            await unitOfWork.SaveChangesAsync();\n            return true;\n        }\n        return false;\n    }\n}\n");
            return this.GenerationEnvironment.ToString();
        }
        
        #line 1 "/home/osqyfr/Desktop/CRUDGen/CRUDGen/Tts/ServiceFile.tt"

private string _DtosNamespaceField;

/// <summary>
/// Access the DtosNamespace parameter of the template.
/// </summary>
private string DtosNamespace
{
    get
    {
        return this._DtosNamespaceField;
    }
}

private string _EntitiesNamespaceField;

/// <summary>
/// Access the EntitiesNamespace parameter of the template.
/// </summary>
private string EntitiesNamespace
{
    get
    {
        return this._EntitiesNamespaceField;
    }
}

private string _EntityNameField;

/// <summary>
/// Access the EntityName parameter of the template.
/// </summary>
private string EntityName
{
    get
    {
        return this._EntityNameField;
    }
}

private string _RepositoryNamespaceField;

/// <summary>
/// Access the RepositoryNamespace parameter of the template.
/// </summary>
private string RepositoryNamespace
{
    get
    {
        return this._RepositoryNamespaceField;
    }
}

private string _ServicesNamespaceField;

/// <summary>
/// Access the ServicesNamespace parameter of the template.
/// </summary>
private string ServicesNamespace
{
    get
    {
        return this._ServicesNamespaceField;
    }
}


/// <summary>
/// Initialize the template
/// </summary>
public virtual void Initialize()
{
    if ((this.Errors.HasErrors == false))
    {
bool DtosNamespaceValueAcquired = false;
if (this.Session.ContainsKey("DtosNamespace"))
{
    this._DtosNamespaceField = ((string)(this.Session["DtosNamespace"]));
    DtosNamespaceValueAcquired = true;
}
if ((DtosNamespaceValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("DtosNamespace");
    if ((data != null))
    {
        this._DtosNamespaceField = ((string)(data));
    }
}
bool EntitiesNamespaceValueAcquired = false;
if (this.Session.ContainsKey("EntitiesNamespace"))
{
    this._EntitiesNamespaceField = ((string)(this.Session["EntitiesNamespace"]));
    EntitiesNamespaceValueAcquired = true;
}
if ((EntitiesNamespaceValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("EntitiesNamespace");
    if ((data != null))
    {
        this._EntitiesNamespaceField = ((string)(data));
    }
}
bool EntityNameValueAcquired = false;
if (this.Session.ContainsKey("EntityName"))
{
    this._EntityNameField = ((string)(this.Session["EntityName"]));
    EntityNameValueAcquired = true;
}
if ((EntityNameValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("EntityName");
    if ((data != null))
    {
        this._EntityNameField = ((string)(data));
    }
}
bool RepositoryNamespaceValueAcquired = false;
if (this.Session.ContainsKey("RepositoryNamespace"))
{
    this._RepositoryNamespaceField = ((string)(this.Session["RepositoryNamespace"]));
    RepositoryNamespaceValueAcquired = true;
}
if ((RepositoryNamespaceValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("RepositoryNamespace");
    if ((data != null))
    {
        this._RepositoryNamespaceField = ((string)(data));
    }
}
bool ServicesNamespaceValueAcquired = false;
if (this.Session.ContainsKey("ServicesNamespace"))
{
    this._ServicesNamespaceField = ((string)(this.Session["ServicesNamespace"]));
    ServicesNamespaceValueAcquired = true;
}
if ((ServicesNamespaceValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("ServicesNamespace");
    if ((data != null))
    {
        this._ServicesNamespaceField = ((string)(data));
    }
}


    }
}


        
        #line default
        #line hidden
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    public class ServiceFileBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
